const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const ts=require('typescript');const React=require('react');const {renderToStaticMarkup}=require('react-dom/server');
const settings=require('../app/lib/dialogue-loader-settings.ts');
function load(file,deps={}){const mod={exports:{}};const source=fs.readFileSync(path.resolve(__dirname,'../app/'+file),'utf8');vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports:mod.exports,window:{},localStorage:{},...deps.globals,require(name){if(name in deps)return deps[name];if(name.endsWith('.css'))return {};if(name==='react'||name==='react/jsx-runtime')return require(name);if(name==='@/app/hooks/usePreferences')return {usePreferences:()=>({prefs:{dialogueLoader:settings.DEFAULT_DIALOGUE_LOADER}})};if(name==='@/app/lib/dialogue-loader-settings'||name==='./dialogue-loader-settings')return settings;throw Error('Unmocked '+name);}});return mod.exports;}
const {DialogueLatticeLoader}=load('components/DialogueLatticeLoader.tsx');
test('corrupt preferences cannot inject CSS, produce non-finite timing or share defaults',()=>{for(const input of [null,[],undefined,'bad'])assert.deepEqual(settings.normalizeDialogueLoader(input),settings.DEFAULT_DIALOGUE_LOADER);const got=settings.normalizeDialogueLoader({color:'url(https://example.com)',step:Infinity,gap:-4,cellSize:900,idleOpacity:NaN,glow:'false'});assert.equal(got.color,'#2020eb');assert.equal(got.step,90);assert.equal(got.gap,1);assert.equal(got.cellSize,12);assert.equal(got.idleOpacity,.3);assert.equal(got.glow,true);got.color='#000000';assert.equal(settings.normalizeDialogueLoader(null).color,'#2020eb');});
test('valid custom colors and parameters survive JSON restoration',()=>{const input={useThemeColor:false,color:'#ABCDEF',step:120,cellSize:11,gap:4,idleOpacity:.5,glow:false};assert.deepEqual(settings.normalizeDialogueLoader(JSON.parse(JSON.stringify(input))),{...input,color:'#abcdef'});});
test('the wave preserves eight distinct perimeter phases and an empty centre at any speed',()=>{for(const step of [50,90,240,NaN]){const cells=settings.dialogueLatticeCells(step);assert.equal(cells.length,9);assert.equal(cells[4].hole,true);assert.equal(cells.filter(x=>x.hole).length,1);assert.equal(new Set(cells.filter(x=>!x.hole).map(x=>x.delay)).size,8);assert.ok(cells.every(x=>Number.isFinite(x.delay)));}});
test('a long real status stays visible and accessible while cells remain decorative',()=>{const html=renderToStaticMarkup(React.createElement(DialogueLatticeLoader,{label:'已排队，等待服务器调度 中文与English/long-id',settings:settings.normalizeDialogueLoader({useThemeColor:false,color:'#2020eb'})}));assert.match(html,/role="status"/);assert.match(html,/aria-live="polite"/);assert.match(html,/已排队，等待服务器调度/);assert.match(html,/--dll-color:#2020eb/);assert.match(html,/data-hole="true"/);assert.match(html,/__grid" aria-hidden="true"/);});
test('paused and button indicators avoid false live announcements; settings do not start clocks',()=>{const paused=renderToStaticMarkup(React.createElement(DialogueLatticeLoader,{label:'任务已暂停',animate:false}));assert.match(paused,/data-animated="false"/);assert.match(paused,/任务已暂停/);const button=renderToStaticMarkup(React.createElement(DialogueLatticeLoader,{compact:true,decorative:true}));assert.doesNotMatch(button,/role="status"|aria-live/);assert.match(button,/aria-hidden="true"/);assert.match(button,/--dll-cell:4px/);const inherited=renderToStaticMarkup(React.createElement(DialogueLatticeLoader,{label:'正在规划',live:false}));assert.doesNotMatch(inherited,/role="status"/);assert.match(inherited,/正在规划/);});
test('preference save stays in the current owner and sends only the recognized new field',()=>{const values=new Map(),sent=[];let owner='A';const localStorage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};const p=load('lib/preferences.ts',{'./server-sync':{savePrefsBatchToServer:async x=>sent.push(x)},'./data-owner':{currentDataOwner:()=>owner,workspaceDataKey:(o,k)=>o+':'+k},'./preference-values':require('../app/lib/preference-values.ts'),'./galaxy-settings':require('../app/lib/galaxy-settings.ts'),'./coze-dialogue-settings':require('../app/lib/coze-dialogue-settings.ts'),globals:{window:{},localStorage}});p.savePreferences({dialogueLoader:{useThemeColor:false,color:'#123456'},injected:'ignored'});assert.equal(p.getPreferences().dialogueLoader.color,'#123456');assert.deepEqual(Object.keys(sent[0]),['dialogueLoader']);owner='B';assert.equal(p.getPreferences().dialogueLoader.useThemeColor,true);p.savePreferences({dialogueLoader:{color:'#abcdef'}});owner='A';assert.equal(p.getPreferences().dialogueLoader.color,'#123456');});

test('only the current request ID and session can show a thinking state; history and stopped requests cannot',()=>{const p={id:'current',sessionId:'A'};assert.equal(settings.isPendingDialogueReply(p,'current','A',true),true);for(const args of [[null,'current','A',true],[p,'historical','A',true],[p,'current','B',true],[p,'current','A',false]])assert.equal(settings.isPendingDialogueReply(...args),false);});
