"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),Module=require("node:module"),ts=require("typescript");
function compile(file, mockAuth) { const mod=new Module(file,module);mod.filename=file;mod.paths=Module._nodeModulePaths(path.dirname(file));const native=mod.require.bind(mod);mod.require=name=>name==="./auth"&&mockAuth?mockAuth:native(name);mod._compile(ts.transpileModule(fs.readFileSync(file,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,file);return mod.exports; }
function load(){const auth=compile(path.resolve("app/lib/auth.ts"));return compile(path.resolve("app/lib/weather.ts"),auth);}
function current(){return{temp:23,text:"多云",icon:"101",humidity:65,windDir:"东北风",windScale:2,feelsLike:24,city:"深圳",updateTime:Date.now()};}
async function fixture(run){const old={window:global.window,localStorage:global.localStorage,fetch:global.fetch};const values=new Map();const oldBase=process.env.NEXT_PUBLIC_AGENT_BACKEND_URL;delete process.env.NEXT_PUBLIC_AGENT_BACKEND_URL;global.window={location:{protocol:"http:",hostname:"local-fixture.test",port:"",origin:"http://local-fixture.test"}};global.localStorage={getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value)};try{await run(load(),values);}finally{if(oldBase===undefined)delete process.env.NEXT_PUBLIC_AGENT_BACKEND_URL;else process.env.NEXT_PUBLIC_AGENT_BACKEND_URL=oldBase;for(const[k,v]of Object.entries(old)){if(v===undefined)delete global[k];else global[k]=v;}}}
test("the client requests only its application weather endpoint without a provider credential",async()=>fixture(async weather=>{let sent;global.fetch=async(url,options)=>{sent={url,options};return{ok:true,json:async()=>({available:true,data:current()})}};assert.equal((await weather.fetchWeather()).temp,23);assert.equal(sent.url,"http://local-fixture.test/api/weather");assert.equal(sent.options.headers,undefined);assert.equal(sent.options.cache,"no-store");}));
test("legacy direct-provider cache is not presented as a confirmed new proxy result",async()=>fixture(async(weather,values)=>{values.set("tszh_weather",JSON.stringify(current()));let calls=0;global.fetch=async()=>{calls++;return{ok:true,json:async()=>({available:false,reason:"NOT_CONFIGURED"})}};assert.equal(await weather.fetchWeather(),null);assert.equal(calls,1);}));
test("a fresh confirmed result is cached but corrupt or non-finite cache values are rejected",async()=>fixture(async(weather,values)=>{let calls=0;global.fetch=async()=>{calls++;return{ok:true,json:async()=>({available:true,data:current()})}};await weather.fetchWeather();await weather.fetchWeather();assert.equal(calls,1);values.set("tszh_weather_v2",JSON.stringify({...current(),temp:null}));await weather.fetchWeather();assert.equal(calls,2);}));
test("storage denial does not discard an otherwise confirmed weather response",async()=>fixture(async weather=>{global.localStorage.setItem=()=>{throw Error("denied")};global.fetch=async()=>({ok:true,json:async()=>({available:true,data:current()})});assert.equal((await weather.fetchWeather()).temp,23);}));
test("offline, unavailable and malformed results return no fabricated forecast",async()=>fixture(async weather=>{for(const response of [{ok:false},{ok:true,json:async()=>({available:false})},{ok:true,json:async()=>({available:true,data:{...current(),temp:"NaN"}})}]){global.fetch=async()=>response;assert.equal(await weather.fetchWeather(),null);}global.fetch=async()=>{throw Error("offline")};assert.equal(await weather.fetchWeather(),null);}));
test("thunderstorm weather does not fall through the generic rain classification",()=>{const weather=load();assert.equal(weather.getWeatherMood("302"),"stormy");assert.equal(weather.getWeatherMood("304"),"stormy");assert.equal(weather.getWeatherMood("305"),"rainy");});


test("the real application resolver maps the split development port to the backend",async()=>fixture(async weather=>{global.window.location={protocol:"http:",hostname:"local-fixture.test",port:"3000",origin:"http://local-fixture.test:3000"};let url;global.fetch=async value=>{url=value;return{ok:true,json:async()=>({available:false})}};assert.equal(await weather.fetchWeather(),null);assert.equal(url,"http://local-fixture.test:8080/api/weather");}));
