// 研究运行工作台 — Mock 演示数据
// 规划 Task 2 Step 4：演示输入"赛博朋克"+"国产工业机器人 8 秒产品短片"；
// 至少 6 条演示来源、3 个产物；所有来源标注为演示数据，不得伪装真实联网结果。

import type {
  ResearchPlan,
  SourceArtifact,
  OutputArtifact,
  StyleResearchInput,
} from "./types";

// 纯类型 import，type-stripping 后消失

export function buildDemoPlan(input: StyleResearchInput): ResearchPlan {
  const objective = `研究「${input.styleName}」风格并生成面向「${input.useCase}」的应用方案`;
  return {
    revision: 1,
    objective,
    budget: "standard",
    estimatedCalls: 4,
    steps: [
      {
        id: "step-opc-context",
        title: "读取 OPC 创作上下文",
        description: "拉取当前项目的风格前缀、时长、画幅与运镜偏好，作为后续步骤的输入。",
        kind: "tool",
        tool: "get_opc_context",
        optional: false,
        enabled: true,
        dependsOn: [],
        input: {},
        status: "pending",
      },
      {
        id: "step-web-research",
        title: `调研「${input.styleName}」视觉特征`,
        description: "公开网络检索该风格的色彩、光影、构图与代表作品资料。",
        kind: "tool",
        tool: "web_search",
        optional: false,
        enabled: true,
        dependsOn: ["step-opc-context"],
        input: { query: `${input.styleName} 视觉风格 色彩 光影 构图` },
        status: "pending",
      },
      {
        id: "step-rag-verify",
        title: "知识库交叉核对",
        description: "用项目知识库核对调研要点，标记可信条目。",
        kind: "tool",
        tool: "rag_search",
        optional: true,
        enabled: true,
        dependsOn: ["step-web-research"],
        input: { query: `${input.styleName} 风格要点` },
        status: "pending",
      },
      {
        id: "step-feature-pack",
        title: "提取风格特征包",
        description: "汇总色彩、光影、构图、材质、关键词与负面约束，产出结构化特征包。",
        kind: "model",
        tool: null,
        optional: false,
        enabled: true,
        dependsOn: ["step-web-research", "step-rag-verify"],
        input: {},
        status: "pending",
      },
      {
        id: "step-apply-pack",
        title: "生成应用提示词方案",
        description: `针对「${input.useCase}」生成中英提示词、运镜建议与避坑要点。`,
        kind: "model",
        tool: null,
        optional: false,
        enabled: true,
        dependsOn: ["step-feature-pack"],
        input: {},
        status: "pending",
      },
    ],
  };
}

export function buildDemoSources(styleName: string): SourceArtifact[] {
  const prefix = styleName || "目标风格";
  return [
    {
      id: "demo-src-1",
      sourceType: "web",
      title: `${prefix}色彩体系综述（演示来源）`,
      url: "https://example.com/demo/cyberpunk-color",
      domain: "example.com",
      publishedAt: "2026-06-01T00:00:00.000Z",
      retrievedAt: "2026-08-29T00:00:02.000Z",
      excerpt: "霓虹主色 + 高对比暗部 + 青洋红撞色是该风格最常见的色彩结构（演示数据）。",
      toolCallId: "tc-web-1",
      citedBy: ["demo-art-1"],
      trust: "untrusted",
    },
    {
      id: "demo-src-2",
      sourceType: "web",
      title: `${prefix}光影语言分析（演示来源）`,
      url: "https://example.com/demo/cyberpunk-lighting",
      domain: "example.com",
      publishedAt: "2026-05-20T00:00:00.000Z",
      retrievedAt: "2026-08-29T00:00:03.000Z",
      excerpt: "强侧逆光、体积雾与霓虹反射构成标志性夜景氛围（演示数据）。",
      toolCallId: "tc-web-1",
      citedBy: ["demo-art-1"],
      trust: "untrusted",
    },
    {
      id: "demo-src-3",
      sourceType: "web",
      title: `${prefix}构图与镜头运动案例（演示来源）`,
      url: "https://example.com/demo/cyberpunk-composition",
      domain: "example.com",
      publishedAt: "2026-04-11T00:00:00.000Z",
      retrievedAt: "2026-08-29T00:00:04.000Z",
      excerpt: "低角度仰拍 + 前景遮挡 + 缓慢推轨在同类短片中使用频率最高（演示数据）。",
      toolCallId: "tc-web-1",
      citedBy: ["demo-art-1", "demo-art-3"],
      trust: "untrusted",
    },
    {
      id: "demo-src-4",
      sourceType: "web",
      title: `${prefix}材质与雨夜反射参考（演示来源）`,
      url: "https://example.com/demo/cyberpunk-material",
      domain: "example.com",
      publishedAt: "2026-03-08T00:00:00.000Z",
      retrievedAt: "2026-08-29T00:00:05.000Z",
      excerpt: "湿润沥青 + 金属漆面 + 全息投影广告牌是常用材质组合（演示数据）。",
      toolCallId: "tc-web-2",
      citedBy: ["demo-art-1"],
      trust: "untrusted",
    },
    {
      id: "demo-src-5",
      sourceType: "rag",
      title: "项目知识库：风格要点核对（演示来源）",
      url: null,
      domain: null,
      publishedAt: null,
      retrievedAt: "2026-08-29T00:00:06.000Z",
      excerpt: "知识库命中：该风格与本产品此前「智能机械」项目高度兼容，注意负面约束包含过曝（演示数据）。",
      toolCallId: "tc-rag-1",
      citedBy: ["demo-art-2"],
      trust: "project_knowledge",
    },
    {
      id: "demo-src-6",
      sourceType: "rag",
      title: "项目知识库：运镜参数偏好（演示来源）",
      url: null,
      domain: null,
      publishedAt: null,
      retrievedAt: "2026-08-29T00:00:07.000Z",
      excerpt: "知识库命中：8 秒产品短片建议 2 段运镜，避免超过 3 次切换（演示数据）。",
      toolCallId: "tc-rag-1",
      citedBy: ["demo-art-3"],
      trust: "project_knowledge",
    },
  ];
}

export function buildDemoArtifacts(input: StyleResearchInput): OutputArtifact[] {
  const styleName = input.styleName || "目标风格";
  const featurePack = {
    color: ["霓虹青 #22E0E6", "洋红 #E84FD0", "深空底 #0A0E1C", "暖点缀 #E89840"],
    lighting: ["强侧逆光", "体积雾", "霓虹反射", "局部过曝控制"],
    composition: ["低角度仰拍", "前景遮挡", "三层景深", "中心偏移主体"],
    material: ["湿润沥青", "金属漆面", "全息投影", "磨砂塑料"],
    keywords: ["cyberpunk", "neon noir", "futuristic industrial", "rainy night"],
    negative: ["过曝", "纯白背景", "低对比", "卡通渲染"],
  };
  return [
    {
      id: "demo-art-1",
      type: "style-feature-pack",
      title: `${styleName} 风格特征包`,
      mimeType: "application/json",
      fileName: "style-feature-pack.json",
      content: JSON.stringify(featurePack, null, 2),
      createdAt: "2026-08-29T00:01:00.000Z",
      sourceIds: ["demo-src-1", "demo-src-2", "demo-src-3", "demo-src-4"],
    },
    {
      id: "demo-art-2",
      type: "research-report",
      title: `${styleName} 风格研究报告`,
      mimeType: "text/markdown",
      fileName: "research-report.md",
      content: [
        `# ${styleName} 风格研究报告`,
        "",
        `> 应用场景：${input.useCase}`,
        "",
        "## 一、视觉特征",
        `- 色彩：霓虹青 + 洋红撞色，深空暗底 [1][2]`,
        `- 光影：强侧逆光与体积雾构建纵深 [2]`,
        `- 构图：低角度仰拍 + 前景遮挡 [3]`,
        "",
        "## 二、可信度说明",
        "本报告基于演示来源生成，正式接入后将替换为真实检索结果。",
        "",
        "## 引用",
        "[1] 色彩体系综述（演示） [2] 光影语言分析（演示） [3] 构图案例（演示）",
      ].join("\n"),
      createdAt: "2026-08-29T00:01:10.000Z",
      sourceIds: ["demo-src-1", "demo-src-2", "demo-src-3", "demo-src-4", "demo-src-5"],
    },
    {
      id: "demo-art-3",
      type: "application-prompt-pack",
      title: `${input.useCase} 应用提示词方案`,
      mimeType: "text/markdown",
      fileName: "application-prompt-pack.md",
      content: [
        `# ${styleName} × ${input.useCase}`,
        "",
        "## 中文提示词",
        "霓虹雨夜工业场景，低角度仰拍国产工业机器人，金属漆面反射青洋红霓虹，体积雾纵深，缓慢推轨。",
        "",
        "## English Prompt",
        "Cyberpunk rainy industrial scene, low-angle shot of a Chinese industrial robot, metallic paint reflecting cyan and magenta neon, volumetric fog depth, slow dolly-in.",
        "",
        "## 运镜建议",
        "1. 0-3s 缓慢推轨建立主体；2. 3-8s 侧面弧形跟随展示细节。",
        "",
        "## 避坑要点",
        "- 避免过曝霓虹（负面约束）",
        "- 8 秒内不超过 2 次运镜切换（知识库命中）",
      ].join("\n"),
      createdAt: "2026-08-29T00:01:20.000Z",
      sourceIds: ["demo-src-3", "demo-src-6"],
    },
  ];
}
